db:
  # plocal might be used only if server not started (start: false)!
#  uri: 'plocal:/tmp/db/databases/sample'
  uri: 'remote:localhost/sample'
  user: 'custom'
  pass: 'custompwd'

orient-server:
  files-path: $TMP/db/
  start: true

  config:
    users:
      - name: root
        password: root
        resources: '*'

    handlers:
      - clazz: 'com.orientechnologies.orient.server.handler.OJMXPlugin'
        parameters:
          - name: enabled
            value: true
          - name: profilerManaged
            value: true
      - clazz: 'com.orientechnologies.orient.server.handler.OAutomaticBackup'
        parameters:
          - name: enabled
            value: false
          - name: delay
            value: 4h
          - name: target.directory
            value: backup
          - name: target.fileName
            value: '${DBNAME}-${DATE:yyyyMMddHHmmss}.json'
          - name: compressionLevel
            value: 9
          - name: bufferSize
            value: 1048576
          - name: db.include
            value:
          - name: db.exclude
            value:
      - clazz: 'com.orientechnologies.orient.server.handler.OServerSideScriptInterpreter'
        parameters:
          - name: enabled
            value: false

    network:
      protocols:
        - name: binary
          implementation: 'com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary'
        - name: http
          implementation: 'com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpDb'
      listeners:
        - protocol: binary
          ipAddress: 0.0.0.0
          portRange: 2424-2430
        - protocol: http
          ipAddress: 0.0.0.0
          portRange: 2480-2490
          parameters:
            - name: network.http.charset
              value: utf-8
          commands:
            - pattern: 'GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg'
              implementation: 'com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent'
              parameters:
                - name: 'http.cache:*.htm *.html'
                  value: 'Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache'
                - name: 'http.cache:default'
                  value: 'Cache-Control: max-age=120'
    # enable below lines if graph version used
    #            - pattern: 'GET|gephi/*'
    #              implementation: 'com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi'

    properties:
      - name: db.pool.min
        value: 1
      - name: db.pool.max
        value: 50
        # for multi-threaded environment level1 cache bound to thread - not much sense in it, but may be usefull in rare situations
      - name: cache.level1.enabled
        value: true
        # datastore cache (global cache)
      - name: cache.level2.enabled
        value: true
        # no restriction for cache size
      - name: cache.level2.size
        value: -1
        #important for embedded mode, because in other case "no ORIENT_HOME" warnings will be in logs
      - name: plugin.dynamic
        value: false
      - name: profiler.enabled
        value: true
        #configures the profiler as <seconds-for-snapshot>,<archive-snapshot-size>,<summary-size>
      - name: profiler.config
        value: '30,10,10'
      - name: log.console.level
        value: fine
      - name: log.file.level
        value: info

server:
  rootPath: '/rest/*'

  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9090

logging:
  level: INFO

  loggers:
    ru.vyarus.app.todo: INFO

